// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obffhqawrjpbuqwlwwxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZmZocWF3cmpwYnVxd2x3d3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNDUzODcsImV4cCI6MjA1NDkyMTM4N30.QVXDxhXsei6lOUclKX0MIm1u9aavEsc59FSml3fe3EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);